os: osx
language: generic
before_install:
  - brew install tfenv
  - tfenv install 0.12.29
  - tfenv use 0.12.29
  - brew install aliyun-cli
  - brew install jq
  - brew install kubectx
  - pip3 install pyyaml
deploy:
  provider: script
  script: sh scripts/deploy-destroy.sh
  on:
    branch: master
# in case of deploy/destroy failed, we run it again hoping to fix the resource leftover
after_deploy: sh scripts/clean.sh

notifications:
  email:
    - yagrxu@gmail.com